# Generated by Django 5.0.2 on 2024-02-28 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available_to_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='renters_history',
            field=models.ManyToManyField(related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='car',
            name='renter',
        ),
        migrations.AddField(
            model_name='car',
            name='renter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
